import React from "react"
import type { Metadata, Viewport } from "next"
import { Inter, Playfair_Display } from "next/font/google"
import { Analytics } from "@vercel/analytics/next"
import { ThemeProvider } from "@/components/theme-provider"
import { PortfolioProvider } from "@/lib/portfolio-context"
import { FloatingChat } from "@/components/floating-chat"
import { Toaster } from "@/components/ui/toaster"
import "./globals.css"

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" })
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
})

export const metadata: Metadata = {
  title: "Olalekan Abayomi | Full-Stack Developer & Digital Artist",
  description:
    "Portfolio of Olalekan Abayomi - A passionate full-stack developer and digital artist creating beautiful, functional digital experiences.",
  keywords: [
    "developer",
    "portfolio",
    "web development",
    "digital art",
    "illustration",
    "full-stack",
    "React",
    "Next.js",
  ],
  authors: [{ name: "Olalekan Abayomi" }],
  creator: "Olalekan Abayomi",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://OlalekanAbayomi.com",
    title: "Olalekan Abayomi | Full-Stack Developer & Digital Artist",
    description:
      "Portfolio of Olalekan Abayomi - A passionate full-stack developer and digital artist.",
    siteName: "Olalekan Abayomi Portfolio",
  },
  twitter: {
    card: "summary_large_image",
    title: "Olalekan Abayomi | Full-Stack Developer & Digital Artist",
    description:
      "Portfolio of Olalekan Abayomi - A passionate full-stack developer and digital artist.",
    creator: "@OlalekanAbayomi",
  },
  icons: {
    icon: [
      { url: "/icon-light-32x32.png", media: "(prefers-color-scheme: light)" },
      { url: "/icon-dark-32x32.png", media: "(prefers-color-scheme: dark)" },
      { url: "/icon.svg", type: "image/svg+xml" },
    ],
    apple: "/apple-icon.png",
  },
}

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f8fafc" },
    { media: "(prefers-color-scheme: dark)", color: "#0f172a" },
  ],
  width: "device-width",
  initialScale: 1,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${playfair.variable} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PortfolioProvider>
            {children}
            <FloatingChat />
            <Toaster />
          </PortfolioProvider>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  )
}






// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
